spring.application.name=Book_Store
#Begin config connect database
spring.datasource.url=jdbc:mysql://localhost:8811/bookstore_test
spring.datasource.username=root
spring.datasource.password=dinhpham
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#End config connect database

# C?u hình cho multipart uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# key

# Cloudinary Configuration
cloudinary.cloud_name=cloudshopdev
cloudinary.api_key=637694883369659
cloudinary.api_secret=UCgOLXuf_Oo3D1pSqnFliQeRkek
cloudinary.secure=true

# PayOS Configuration
payos.client-id=9839db1c-a791-4996-b43b-7032bd5d93ad
payos.api-key=e9696bbf-e940-46dc-95e8-96f6301f31a2
payos.checksum-key=7f25c3ae883e3c493672360d9b9f3f4d6af2adbcdf77dae1cf0c335b4c7a668e

# Application base URL for constructing callback/webhook URLs
app.base-url=http://localhost:8080

openai.api_key=AIzaSyBOsQ-O-hcmWUFOyaqMxw0Ssf7Uicnr7L4

#logging.level.org.springframework.security=DEBUG